// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdYzXavjDY5cvWsmwdIpleA6Xps0B6XnA',
    appId: '1:278875593512:android:45e1a5a2c65d16f18e8e1d',
    messagingSenderId: '278875593512',
    projectId: 'i-chat-instant',
    databaseURL: 'https://i-chat-instant-default-rtdb.firebaseio.com',
    storageBucket: 'i-chat-instant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuzWvQgS_Tlig1USupOKFDwhfWMR1FVP8',
    appId: '1:278875593512:ios:7cb48fdbc6e0ec228e8e1d',
    messagingSenderId: '278875593512',
    projectId: 'i-chat-instant',
    databaseURL: 'https://i-chat-instant-default-rtdb.firebaseio.com',
    storageBucket: 'i-chat-instant.appspot.com',
    iosClientId: '278875593512-lgd78flp7kjmof9e2kb0ur460d7d6n9o.apps.googleusercontent.com',
    iosBundleId: 'com.usamamuzaffar.iChatInstant',
  );
}
